### ISSUE TITLE
Get emissivity for lines observed in chosen EIS map

### ISSUE THREAD

**Issue by dstansby** [dstansby/demcmc#2]

**Comment by andyto1234** [comment]
Emissivity done! The file has been uploaded to the link as it's quite big (~600Mb).

Teia's density map has a dimension of  [123,512]. So I created a 4 dimensional array that has the output (for e.g. pixel 10,15 ) emissivity = [*,*,10,15]. 13 lines where included according to the order saved in another variable "lineid".

Link to emissivity: https://liveuclac-my.sharepoint.com/:u:/g/personal/zcicsht_ucl_ac_uk/EZyyCuK2cKpGpPPaviCrotgBSKsEe3tSBc90jwdf33kQuA?e=kAr8aL

**Comment by andyto1234** [comment]
Oops sorry to mention that I have skipped all the densities with a value of -100. These just mean bad fit in the IDL eis density routine. Emissivities over these pixels are just filled with 0s.
