### ISSUE TITLE
Release on PyPI

### ISSUE THREAD

**Issue by dstansby** [dstansby/demcmc#54]

**Comment by BogdanMFometescu** [comment]
#This are the basic steps to release a package to PyPi
##1 . Create a setup.py file 
##2. Build the package files
##3. Create account on Pypi
##4. Publish  it on PyPi using twine

###1. The file setup.py should look like this:
```Python
from setuptools import setup, find_packages

VERSION = '0.0.1'
DESCRIPTION = 'A conversion package'
LONG_DESCRIPTION = 'A package that makes it easy to convert values between several units of measurement'

setup(
    name="convrsn",
    version=VERSION,
    description=DESCRIPTION,
    long_description=LONG_DESCRIPTION,
    author="<Your Name>",
    author_email="<your email>",
    license='MIT',
    packages=find_packages(),
    install_requires=[],
    keywords='conversion',
    classifiers= [
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        'License :: OSI Approved :: MIT License',
        "Programming Language :: Python :: 3",
    ]
)

```
###2 Build the package file 
```Python
python setup.py sdist bdist_wheel
```


###3 Create account on PyPi 
[Register](https://pypi.org/account/register/)

###4 Publish the package 
```Python
pip install twine 
twine upload --repository testpypi dist/*
```
 
Full steps are on this [link](https://circleci.com/blog/publishing-a-python-package/?utm_source=google&utm_medium=sem&utm_campaign=sem-google-dg--emea-en-dsa-tROAS-auth-nb&utm_term=g_-_c__dsa_&utm_content=&gclid=CjwKCAiAu5agBhBzEiwAdiR5tFXeWsKMNye41UYcToJIcJNW7W-PS1VasSNj7oeOONdgRmfPBSOlxRoCuucQAvD_BwE)

Hope this helps.
